# Generated by Django 4.0.6 on 2022-07-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0002_booking_schedule_remove_player_date_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gametime.player'),
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gametime.schedule'),
        ),
    ]
