# Generated by Django 4.0.6 on 2022-07-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0004_tag_booking_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingnum',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting for players...', 'waiting for players...'), ('Complete Players', 'Complete Players'), ('Rescheduled', 'Rescheduled'), ('Now Playing', 'Now Playing'), ('Game Ended', 'Game Ended')], max_length=200, null=True),
        ),
    ]
