# Generated by Django 4.0.6 on 2022-07-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0006_remove_booking_bookingnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='schedule',
            new_name='court',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='court',
            field=models.CharField(choices=[('Eastwood Ph1', 'Eastwood Ph1'), ('Eastwood Ph2', 'Eastwood Ph2'), ('Diliman', 'Diliman'), ('Eastwind', 'Eastwind'), ('Centella', 'Centella')], max_length=200, null=True),
        ),
    ]
