# Generated by Django 4.0.6 on 2022-07-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0007_rename_schedule_booking_court_alter_schedule_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_booked',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tags',
        ),
        migrations.AddField(
            model_name='booking',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gametime.tag'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.CharField(choices=[('5:00PM-6:00PM', '5:00PM-6:00PM'), ('6:00PM-7:00PM', '6:00PM-7:00PM'), ('7:00PM-8:00PM', '7:00PM-8:00PM'), ('8:00PM-9:00PM', '8:00PM-9:00PM')], max_length=200, null=True),
        ),
    ]
