# Generated by Django 4.0.6 on 2022-07-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0008_remove_schedule_date_booked_remove_schedule_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tags',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
