# Generated by Django 4.0.6 on 2022-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0010_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
