# Generated by Django 4.0.6 on 2022-07-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0011_player_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='court',
            new_name='schedule',
        ),
    ]
