# Generated by Django 4.0.6 on 2022-07-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0012_rename_court_booking_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('waiting for players...', 'waiting for players...'), ('Complete Players', 'Complete Players'), ('Rescheduled', 'Rescheduled'), ('Now Playing', 'Now Playing'), ('Game Ended', 'Game Ended')], max_length=200, null=True),
        ),
    ]
