# Generated by Django 4.0.6 on 2022-08-13 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gametime', '0013_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gametime.tag'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting for players...', 'waiting for players...'), ('Complete Players', 'Complete Players'), ('Rescheduled', 'Rescheduled'), ('Now Playing', 'Now Playing'), ('Game Ended', 'Game Ended')], max_length=200, null=True),
        ),
    ]
