# Generated by Django 4.0.6 on 2022-08-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gametime', '0015_alter_player_age_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gametime.player'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gametime.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='court',
            field=models.CharField(blank=True, choices=[('Eastwood Ph1', 'Eastwood Ph1'), ('Eastwood Ph2', 'Eastwood Ph2'), ('Diliman', 'Diliman'), ('Eastwind', 'Eastwind'), ('Centella', 'Centella')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.CharField(blank=True, choices=[('5:00PM-6:00PM', '5:00PM-6:00PM'), ('6:00PM-7:00PM', '6:00PM-7:00PM'), ('7:00PM-8:00PM', '7:00PM-8:00PM'), ('8:00PM-9:00PM', '8:00PM-9:00PM')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='statman',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='payment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
